### ISSUE TITLE
flash_range_erase_and_program hangs

### ISSUE THREAD

**Issue by chrontax** [jannic/rp2040-flash#11]
Code:
```rs
unsafe {
        let init_flag = read_volatile(0x10100000 as *const [u8; 256]);
        if init_flag != INWOKACJA {
            cortex_m::interrupt::free(|_cs| {
                flash_range_erase_and_program(0x100000, &[0; NODE_TABLE_SIZE], true);
            });
        }
    }
```

**Comment by jannic** [comment]
The length parameter to `flash_range_erase_and_program` seems wrong. And in fact should trigger an error like "expected `u32`, found `&[{integer}; ...]`".

Anyway, I can't get much from such a short code snipped. Can you provide a small demo project which reproduces the issue?

**Comment by chrontax** [comment]
I already solved it, just forgot to say it here. Anyways, what worked for some reason was separating the write to another function
