### ISSUE TITLE
Duplicate symbols in build

### ISSUE THREAD

**Issue by m5p3nc3r** [jannic/rp2040-flash#6]
Hi guys

I am trying to use this crate in my project, but am having issues with duplicate symbols in the linking stage.

This is because I am using the latest rp2040-hal (0.7.0) and this project is using 0.6.1.  Is it possible to create a version of this crate against the latest rp2040-hal?

I understand I can use the crate patch mechanism to solve this, and will give that a try in the short term, if this works for me, do you want me to create a PR to update the hal version?

**Comment by jannic** [comment]
The version in git actually already depends on rp2040-hal 0.8.0. But the release 0.1.1 was rather old and still based on rp2040-hal 0.6.1.

I just released new version of rp2040-flash: Version 0.2.0 using rp2040-hal 0.7.0, and version 0.3.0 using rp2040-hal 0.8.0. So you can use whatever version you need.

Thanks for your offer to provide a PR! In this case, it wasn't needed as all I had to do is to prepare the releases. But in general, contributions are of course welcome.

I think what this project definitely needs is some documentation.
